### ISSUE TITLE
More Options

### ISSUE THREAD

**Issue by alexisbertin** [turbulent/lorco#9]
- [ ] HEX values option (only RGBA so far)
- [ ] SASS Context: Colors returned as maps 
- [ ] CSS Variables: Extra option to work w/ SASS (variables w/ fallback) (c.f. snippet in comment)

**Comment by alexisbertin** [comment]
```

**Comment by alexisbertin** [comment]
```
$colors: (
  red:   #ff0000,
  green: #00ff00,
  blue:  (
    pure: #0000ff,
    navy: #0000fe
  )
);


:root {
  // for each variable map
  @each $var-name, $val in $colors {
    @if type-of($val) == map {
      @each $var-n, $val-n in $val {
        --color-#{$var-name}-#{$var-n}: #{$val-n};
      }
    } @else {
      --color-#{$var-name}: #{$val};
    }
  
  }
}


.foo {
  --foo-bg-color: var(--color-red);
  background-color: var(--foo-bg-color, map-get($colors, red));
  
  @media screen and (max-width: 1000px) {
    --foo-bg-color: var(--color-green);
  }
}
```

**NOTE:** Can't remember if IE11's interpreting `var(--foo-bg-color, map-get($colors, red))` as expected or if we need to declare the property twice as:
```
background-color: map-get($colors, green);
background-color: var(--color-green);
```

**NOTE 2**: Some polyfills exists to convert CSS var into their values but I never found one that works properly with "local" variables (that aren't declared in `:root`) such as `--foo-bg-color` here.

**NOTE 3**: A `map-deep-geet()` function would be needed to access deep map levels. 
i.e `map-deep-get($colors, blue, navy)`.

**Comment by psaunders** [comment]
I think we could take Hex (1), CSS vars are already in there (3).

**Comment by Tonours** [comment]
Close issue since Hexa colors are now part of Lorco
